### ISSUE TITLE
ToDo / Ideas

### ISSUE THREAD

**Issue by cngodles** [cngodles/temporal-range#2]
- [ ] Select a start/end time or eon/period/epoch
- [ ] Inclusion of the stages
- [ ] Making optional any of the 4 chart bars
- [ ] Ability to stack multiple items on the chart for comparisons (Showing range of a genus vs a species, or comparing different species)
- [ ] Ability to add just a single point rather than a range.
- [x] Ability to show chart vertically
- [ ] Colorless Version
- [ ] Double Resolution or settable resolution.
